### ISSUE TITLE
Doesn't work with "vite build"

### ISSUE THREAD

**Issue by peter50216** [mathe42/vite-plugin-worker#5]
When trying to run "vite build" with project that use this and vite-plugin-comlink, the following error will be thrown:

```
[worker:worker] Could not load worker:comlink@worker:/src/workers/mp4-decoder.ts (imported by comlink@main:worker:comlink@worker:/src/workers/mp4-decoder.ts): At build you can not watch files!
error during build:
Error: Could not load worker:comlink@worker:/src/workers/mp4-decoder.ts (imported by comlink@main:worker:comlink@worker:/src/workers/mp4-decoder.ts): At build you can not watch files!
    at bundle (<path>/node_modules/.pnpm/vite-plugin-bundle@1.0.0_vite@2.5.10/node_modules/vite-plugin-bundle/dist/index.js:24178:11)
    at Object.load (<path>/node_modules/.pnpm/vite-plugin-worker@1.0.3_typescript@4.4.3+vite@2.5.10/node_modules/vite-plugin-worker/dist/index.js:259:64)
    at <path>/node_modules/.pnpm/rollup@2.56.2/node_modules/rollup/dist/shared/rollup.js:20199:25
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
 ELIFECYCLE  Command failed with exit code 1.
```

From the error message looks like the issue is in this plugin.

**Comment by mathe42** [comment]
fixed in 1.0.4
